export const SUBMIT_STUDENT_FORM = "SUBMIT_STUDENT_FORM";
export const SUBMIT_STUDENT_FORM_SUCCESS = "SUBMIT_STUDENT_FORM_SUCCESS";
export const SUBMIT_STUDENT_FORM_FAILURE = "SUBMIT_STUDENT_FORM_FAILURE";