export const SUBMIT_STUDENT_FORM = "SUBMIT_STUDENT_FORM";
export const SUBMIT_STUDENT_FORM_SUCCESS = "SUBMIT_STUDENT_FORM_SUCCESS";
export const SUBMIT_STUDENT_FORM_FAILURE = "SUBMIT_STUDENT_FORM_FAILURE";

// delete
export const DELETE_STUDENT = "DELETE_STUDENT"; 
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS"; 
export const DELETE_STUDENT_FAILURE = "DELETE_STUDENT_FAILURE"; 